name: Deploy API Tarja

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: lahornilla-cloud

    - name: Build and Deploy
      run: |
        # Construir imagen usando Cloud Build
        gcloud builds submit --tag gcr.io/lahornilla-cloud/api-lh-tarja
        
        # Desplegar en Cloud Run con Cloud SQL (usando el nombre correcto)
        gcloud run deploy apilhtarja \
          --image gcr.io/lahornilla-cloud/api-lh-tarja \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances gestion-la-hornilla:us-central1:gestion-la-hornilla \
          --set-env-vars DATABASE_URL="mysql+pymysql://UserApp:&8y7c()tu9t/+,6`@/lahornilla_base_normalizada?unix_socket=/cloudsql/gestion-la-hornilla:us-central1:gestion-la-hornilla",SECRET_KEY="Inicio01*",JWT_SECRET_KEY="Inicio01*",FLASK_ENV="production",FLASK_DEBUG="0",K_SERVICE="apilhtarja"
