name: Deploy API Tarja

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: lahornilla-cloud

    - name: Build and Deploy
      run: |
        gcloud builds submit --tag gcr.io/lahornilla-cloud/api-lh-tarja
        gcloud run deploy api-lh-tarja \
          --image gcr.io/lahornilla-cloud/api-lh-tarja \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars DB_HOST="34.41.120.220",DB_USER="UserApp",DB_PASSWORD="&8y7c()tu9t/+,6`",DB_NAME="lahornilla_base_normalizada",DB_PORT=3306
