name: Deploy API Tarja

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: lahornilla-cloud

    - name: Build and Deploy
      run: |
        # Construir imagen usando Cloud Build
        gcloud builds submit --tag gcr.io/lahornilla-cloud/apilhtarja
        
        # Desplegar usando el archivo de configuración del servicio
        gcloud run services replace service.yaml --region=us-central1
        
        # Configurar acceso público y Cloud SQL
        gcloud run services update apilhtarja \
          --region=us-central1 \
          --allow-unauthenticated \
          --add-cloudsql-instances gestion-la-hornilla:us-central1:gestion-la-hornilla
